### ISSUE TITLE
Moderation: Tests fail

### ISSUE THREAD

**Issue by fsbraun** [django-cms/djangocms-moderation#235]
Running the unit tests leads to failures (I removed tracebacks of errors that do not lead to a fail). 

Since there have been no changes to the codebase I assume there must have been changes to dependencies which cause the tests to fail:

```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing djangocms_moderation.egg-info/PKG-INFO
writing dependency_links to djangocms_moderation.egg-info/dependency_links.txt
writing requirements to djangocms_moderation.egg-info/requires.txt
writing top-level names to djangocms_moderation.egg-info/top_level.txt
reading manifest file 'djangocms_moderation.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found under directory '*'
adding license file 'LICENSE.txt'
writing manifest file 'djangocms_moderation.egg-info/SOURCES.txt'
running build_ext
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...............
.
......
..
.......s..........................ss.s.......................................................................ss..................FFFF.....FFFFF
.
======================================================================
FAIL: test_add_pages_moderated_children_to_collection (tests.test_views.CollectionItemsViewAddingRequestsTestCase)
A page with multiple moderatable children automatically adds them to the collection
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 240, in test_add_pages_moderated_children_to_collection
    self.assertEqual(stored_collection.count(), 3)
AssertionError: 1 != 3

======================================================================
FAIL: test_add_pages_moderated_duplicated_children_to_collection (tests.test_views.CollectionItemsViewAddingRequestsTestCase)
A page with multiple instances of the same version added to the collection should only
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 306, in test_add_pages_moderated_duplicated_children_to_collection
    self.assertEqual(stored_collection.filter(version=poll_version).count(), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_add_pages_moderated_duplicated_children_to_collection_for_author_only (tests.test_views.CollectionItemsViewAddingRequestsTestCase)
A page with moderatable children created by different authors only automatically adds the current users items
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 352, in test_add_pages_moderated_duplicated_children_to_collection_for_author_only
    self.assertEqual(stored_collection.count(), 2)
AssertionError: 1 != 2

======================================================================
FAIL: test_add_pages_moderated_traversed_children_to_collection (tests.test_views.CollectionItemsViewAddingRequestsTestCase)
A page with moderatable children that also have moderatable children: child within a child
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 426, in test_add_pages_moderated_traversed_children_to_collection
    self.assertEqual(stored_collection.count(), 4)
AssertionError: 1 != 4

======================================================================
FAIL: test_moderation_workflow_node_deletion_1 (tests.test_views.CollectionItemsViewModerationIntegrationTest)
Add pages to a collection to create a tree structure like so:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 1026, in test_moderation_workflow_node_deletion_1
    self._add_pages_to_collection()
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 979, in _add_pages_to_collection
    self.assertEqual(
AssertionError: 2 != 4

======================================================================
FAIL: test_moderation_workflow_node_deletion_2 (tests.test_views.CollectionItemsViewModerationIntegrationTest)
Add pages to a collection to create a tree structure like so:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 1081, in test_moderation_workflow_node_deletion_2
    self._add_pages_to_collection()
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 979, in _add_pages_to_collection
    self.assertEqual(
AssertionError: 2 != 4

======================================================================
FAIL: test_moderation_workflow_node_deletion_3 (tests.test_views.CollectionItemsViewModerationIntegrationTest)
Add pages to a collection to create a tree structure like so:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 1136, in test_moderation_workflow_node_deletion_3
    self._add_pages_to_collection()
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 979, in _add_pages_to_collection
    self.assertEqual(
AssertionError: 2 != 4

======================================================================
FAIL: test_moderation_workflow_node_deletion_4 (tests.test_views.CollectionItemsViewModerationIntegrationTest)
Add pages to a collection to create a tree structure like so:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 1196, in test_moderation_workflow_node_deletion_4
    self._add_pages_to_collection()
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 979, in _add_pages_to_collection
    self.assertEqual(
AssertionError: 2 != 4

======================================================================
FAIL: test_moderation_workflow_node_deletion_5 (tests.test_views.CollectionItemsViewModerationIntegrationTest)
Add pages to a collection to create a tree structure like so:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 1255, in test_moderation_workflow_node_deletion_5
    self._add_pages_to_collection()
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 979, in _add_pages_to_collection
    self.assertEqual(
AssertionError: 2 != 4

======================================================================
FAIL: test_tree_nodes_are_created (tests.test_views.CollectionItemsViewTest)
Moderation request nodes are created with the correct structure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fsbraun/Source/Python/djangocms-moderation/tests/test_views.py", line 751, in test_tree_nodes_are_created
    self.assertEqual(nodes.count(), 6)
AssertionError: 1 != 6

----------------------------------------------------------------------
Ran 203 tests in 15.000s

FAILED (failures=10, skipped=7)
Destroying test database for alias 'default'...
```

**Comment by Aiky30** [comment]
Must be as the last merge to master is a pass. The requirements: https://github.com/django-cms/djangocms-moderation/blob/master/tests/requirements/requirements_base.txt

**Comment by marksweb** [comment]
There seem to be a mixture of issues causing test failures. I've seen an import in djangocms-alias that's fetching something from django-cms which it can't find. Also there's conflicting dependencies on django itself coming from aldryn-forms

**Comment by marksweb** [comment]
There seem to be a mixture of issues causing test failures. I've seen an import in djangocms-alias that's fetching something from django-cms which it can't find. Also there's conflicting dependencies on django itself coming from aldryn-forms
